name: widgets
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  confetti: ^0.7.0
  file_picker: ^5.3.3
  url_launcher: ^6.1.12
  font_awesome_flutter: ^10.5.0
  fl_chart: ^0.63.0
  provider: ^6.0.5
  shimmer: ^3.0.0
  path_provider: ^2.1.0
  invert_colors: ^0.0.4
  latlng: ^0.2.1
  map: ^1.4.1
  geocoding: ^2.1.0
  flutter_native_splash: ^2.3.2
  shared_preferences: ^2.2.0
  flutter_image_compress: ^2.0.4
  permission_handler: ^10.4.3
  mockito: ^5.4.2
  test: ^1.24.3
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

