name: Dart

on:
  push:
    branches:
      - "development*"
  pull_request:
    branches:
      - "development*"

jobs:
  test_onboarding:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: widgets

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: dart-lang/setup-dart@main

      - name: Install dependencies
        run: flutter pub get

      - name: Fix formatting
        run: dart format --output=none --set-exit-if-changed . || true
        continue-on-error: true

      - name: Analyze project source
        run: dart analyze
        continue-on-error: true

      - name: Run tests
        run: dart test
